
on:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: http://48.214.53.180:8080
      - run: |
          :
    permissions:
      actions: read
